DROP TABLE AMR_ORDER_ITEMS;
DROP TABLE AMR_PLACE_ITEMS_MENU;
DROP TABLE AMR_ORDERS;
DROP TABLE AMR_PLACES;
DROP TABLE AMR_USER;
DROP VIEW AMR_ORDER_ITEM_VIEW;
DROP VIEW AMR_ORDER_VIEW;


CREATE TABLE AMR_USER (
  ID       NUMBER(32) PRIMARY KEY NOT NULL,
  USERNAME VARCHAR2(255) UNIQUE,
  PASS     VARCHAR2(255),
  NAME     VARCHAR2(255),
  PHONE_NO VARCHAR2(50)
);

CREATE TABLE AMR_PLACES (
  ID       NUMBER(32) PRIMARY KEY NOT NULL,
  NAME     VARCHAR2(255),
  PHONE_NO VARCHAR2(50)
);

CREATE TABLE AMR_PLACE_ITEMS_MENU (
  ID          NUMBER(32) PRIMARY KEY,
  PLACE_ID    NUMBER(32) REFERENCES amr_places NOT NULL,
  NAME        VARCHAR2(255),
  DESCRIPTION CLOB,
  PRICE       NUMBER(5, 2),
  CONSTRAINT "NON_NEGATIVE_PRICE" CHECK (Price >= 0) ENABLE
);

CREATE TABLE AMR_ORDERS (
  ID            NUMBER(32) PRIMARY KEY           NOT NULL,
  NAME          VARCHAR2(255),
  OWNER_USER_ID NUMBER(32) REFERENCES amr_user   NOT NULL,
  STATUS        VARCHAR2(50),
  PLACE_ID      NUMBER(32) REFERENCES amr_places NOT NULL,
  ORDER_DATE    DATE
);

CREATE TABLE AMR_ORDER_ITEMS (
  ID                 NUMBER(32) PRIMARY KEY                     NOT NULL,
  ORDER_ID           NUMBER(32) REFERENCES amr_orders           NOT NULL,
  PLACE_ITEM_MENU_ID NUMBER(32) REFERENCES amr_place_items_menu NOT NULL,
  USER_ID            NUMBER(32) REFERENCES amr_user             NOT NULL,
  COUNT              NUMBER(10, 0) DEFAULT (1)
);

-- Order view
CREATE OR REPLACE VIEW AMR_ORDER_VIEW AS
  SELECT
    AMR_ORDERS.ID         AS "ID",
    AMR_ORDERS.NAME       AS "ORDER_NAME",
    AMR_USER.NAME         AS "OWNER_NAME",
    AMR_ORDERS.STATUS     AS "STATUS",
    AMR_PLACES.NAME       AS "PLACE_NAME",
    AMR_ORDERS.ORDER_DATE AS "ORDER_DATE"
  FROM AMR_ORDERS
    JOIN AMR_PLACES ON AMR_ORDERS.PLACE_ID = AMR_PLACES.ID
    JOIN AMR_USER ON AMR_ORDERS.OWNER_USER_ID = AMR_USER.ID
  ORDER BY AMR_ORDERS.ORDER_DATE DESC;

-- Order item view
CREATE OR REPLACE VIEW AMR_ORDER_ITEM_VIEW AS
  SELECT
    AMR_ORDER_ITEMS.ID                                 AS "ID",
    AMR_ORDERS.ID                                      AS "ORDER_ID",
    AMR_PLACES.NAME                                    AS "PLACE_NAME",
    AMR_USER.NAME                                      AS "USER_NAME",
    AMR_ORDER_ITEMS.COUNT                              AS "COUNT",
    AMR_PLACE_ITEMS_MENU.PRICE                         AS "PRICE",
    AMR_ORDER_ITEMS.COUNT * AMR_PLACE_ITEMS_MENU.PRICE AS "TOTAL"
  FROM AMR_ORDER_ITEMS
    JOIN AMR_USER ON AMR_ORDER_ITEMS.USER_ID = AMR_USER.ID
    JOIN AMR_PLACE_ITEMS_MENU ON AMR_ORDER_ITEMS.PLACE_ITEM_MENU_ID = AMR_PLACE_ITEMS_MENU.ID
    JOIN AMR_ORDERS ON AMR_ORDER_ITEMS.ORDER_ID = AMR_ORDERS.ID
    JOIN AMR_PLACES ON AMR_ORDERS.PLACE_ID = AMR_PLACES.ID
  WITH CHECK OPTION;

DROP SEQUENCE AMR_USER_ID_SEQUENCE;
CREATE SEQUENCE AMR_USER_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE;

DROP SEQUENCE AMR_PLACES_ID_SEQUENCE;
CREATE SEQUENCE AMR_PLACES_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE;

DROP SEQUENCE AMR_PLACE_ITEMS_ID_SEQUENCE;
CREATE SEQUENCE AMR_PLACE_ITEMS_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE;

DROP SEQUENCE AMR_ORDERS_ID_SEQUENCE;
CREATE SEQUENCE AMR_ORDERS_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE;

DROP SEQUENCE AMR_ORDER_ITEMS_ID_SEQUENCE;
CREATE SEQUENCE AMR_ORDER_ITEMS_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE;
